In [1]:
import pandas as pd
import numpy as np
import re

path = '../data/eniac/'
orderlines = pd.read_csv(path + 'orderlines.csv')
orders = pd.read_csv(path + 'orders.csv')
brands = pd.read_csv(path + 'brands.csv')
products = pd.read_csv(path + 'products.csv')

df_list = [orderlines, orders, brands, products]
files = ['orderlines','orders','brands','products']

orders['created_date'] = pd.to_datetime(orders['created_date'])
orderlines['date'] = pd.to_datetime(orderlines['date'])

In [13]:
# products.loc[11410].price.count('.')

#products.assign(decimal_count=lambda row: row.price.str.count('\.'))

two_dec = products[products.price.str.count('\.')==2]
#two_dec.price = two_dec.price.apply(lambda x: x.replace('.',''))
#two_dec.price = two_dec.price.apply(lambda x: float(x)/1000)
#two_dec = two_dec.price.apply(lambda x: float(x.replace('.','')))/1000
two_dec

'''
digits before first decimal
2 = correct price

'''

orderlines[orderlines.sku=='REP0188']
bad_products = products[products.price.str.count('\.')==2].shape[0]/products.shape[0] * 100
bad_orderlines = orderlines[orderlines.unit_price.str.count('\.')==2].shape[0]/orderlines.shape[0] * 100

bad_products, bad_orderlines

orderlines[orderlines.unit_price.str.count('\.')==2]

,id,id_order,product_id,product_quantity,sku,unit_price,date
6,1119115,299544,0,1,APP1582,1.137.99,2017-01-01 01:17:21
11,1119126,299549,0,1,PAC0929,2.565.99,2017-01-01 02:07:42
15,1119131,299553,0,1,APP1854,3.278.99,2017-01-01 02:14:47
43,1119195,299582,0,1,PAC0961,2.616.99,2017-01-01 08:54:00
59,1119214,299596,0,1,PAC1599,2.873.99,2017-01-01 09:53:11
...,...,...,...,...,...,...,...
293862,1649999,452946,0,1,APP2075,2.999.00,2018-03-14 13:03:33
293887,1650045,527321,0,1,PAC2148,3.497.00,2018-03-14 13:10:15
293889,1650050,527324,0,1,PAC2117,3.075.00,2018-03-14 13:10:56
293911,1650088,527342,0,1,APP2492,1.329.00,2018-03-14 13:24:51
293936,1650135,527364,0,1,APP2491,1.329.00,2018-03-14 13:36:13

In [ ]:
Mac = (r'^Apple Mac|^Apple iMac|^New Mac|^IMAC desktop|^desktop computer')

Accessories = (r'kensington|silicone|belt|deportiva|alarm|flypad|netcam|dell|celly|ik multimedia|glucÃ­metro|u2913wm dell 29 "ultrasharp fhd ips|scanner|netstream|webcam|bookarc|maleta|robot|blood pressure|netgear satellite|led|bracelet|gloves|polaroid|thermometer|home music|living colors|pocket|game capture|laser|scale|detector|gopro|pointer|riser|stylus|cleaner|case|fairbrush|backpack|casing|briefcase|camera|headphones|headset|keyboard|microphone|minidp|monitor|mouse|pen|pencil|screen protector|sleeve|speaker|stand|star wars|station|support|thermostat|apple tv|drone|lamp|p2418d|radiator|stabilizer|keypad|bag|cover')

iPad = (r'ipad')

iPhone = (r'iphone')

Licenses_and_waranties = (r'siri|parallels desktop|quarkpress|microsoft office|repair|adobe|applecare|license|protection|software|installation')

Open_or_refurbished = (r'^\(OPEN\)|^Open|Like New|refurbished|used|second hand')

Other_devices = (r'tablet|wacom intuos|ninebot|wacom cintiq|wacom mobilestudio')

Parts = (r'siren|devolo|hirise|hoco|startech|access point|replacement|bike|ifixit|bell|sonar fish|linksys|newertech|control|photo|hotspot|sonos|locator keys|alarm system|accelsior|video capture|smart plug|spare ball|calibrator|locator bluetooth|security|devolo dlan 500av|router|airport|lock|adapter|battery|box|bulb|cable|charger|cleanser|converter|dimmer|displayport|dock|kit|lightstrips|rack|raid|sensor|sonnet|allegro|startech hdmi|subwoofer|superdrive|switch|usb-c to|glass|charging|dock|hub|powercube|tools|ups|wireless base|ports|lightning|powerhouse base|nonda mini|satechi multiport|adapatdor')

Storage = (r'seagate|sshd|(wd red)|(drobo b810i iscsi san 8 bays)|(western digital)|(owc mercury)|(external enclosure)|thunderbolt|4tb|sdhc|samsung pro|sdhc|(lexar premium sdhc)|(newertech ministack)|(electra 6g ssd 960gb)|jumpdrive|passport|(wd blue 500gb)|nas|20tb|(256gb samsung)|(512gb samsung ssd)|3tb|8tb|capsule|datatraveler|(disk 500gb)|(hard disk)|(hard drive)|memory|qnap|rackstation|rugged|sandisk|samsung|server|transcend|crucial|cloud|(storage unit)|pendrive|hypedrive|ssynology')

iPod = (r'ipod')

Smartwatch = (r'withings|watch|fitbit')



import numpy as np


products_hana = products_hana.assign(Category = '')

condlist = [
            products_hana.name.str.contains(Open_or_refurbished, case=False, regex = True),
            (((products_hana.sku.str[0:3] == 'APP')|(products_hana.sku.str[0:3] == 'PAC')) & (products_hana.name.str.contains(Mac, case=False, regex = True))),
            products_hana.name.str.contains(Smartwatch, case=False, regex = True),
            ((products_hana.name.str.contains(Parts, case=False, regex = True)) & (products_hana.price < 100)),
            products_hana.name.str.contains(Parts, case=False, regex = True),
            ((products_hana.name.str.contains(Accessories, case=False, regex = True)) & (products_hana.price < 200)),
            products_hana.name.str.contains(Accessories, case=False, regex = True),
            products_hana.name.str.contains(Licenses_and_waranties, case=False, regex = True),
            products_hana.name.str.contains(Other_devices, case=False, regex = True),
            ((products_hana.name.str.contains(Storage, case=False, regex = True)) & (products_hana.price < 500)),
            products_hana.name.str.contains(Storage, case=False, regex = True),
            products_hana.name.str.contains(iPad, case=False, regex = True),
            products_hana.name.str.contains(iPhone, case=False, regex = True),
            
            products_hana.name.str.contains(iPod, case=False, regex = True)
]

choicelist = [ 
            'Open or refurbished',
            'Mac',
            'Smartwatch',
            'Cheap parts',
            'Expensive parts',
            'Cheap Accessories',
            'Expensive Accessories',
            'Licenses_and_waranties',
            'Other_devices',
            'Cheap Storage',
            'Expensive storage',
            'iPad',
            'iPhone',
            
            'iPod'
]

products_hana.Category = np.select(condlist, choicelist, default='Uncategorized')